services:
    - postgresql
    - mysql
language: perl6

perl6:
    - latest
sudo: true
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -qq -y libodbc1
    - sudo apt-get install -qq -y libmyodbc
    - sudo apt-get install -qq -y odbc-postgresql
    # mysql
    - mysql -e "CREATE DATABASE dbdishtest;" -uroot
    - mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpass';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON dbdishtest.* TO 'testuser'@'localhost';" -uroot
    # Pg
    - psql -c 'CREATE DATABASE dbdishtest;' -U postgres
